language: go
go:
  - 1.7
  - 1.6
  - 1.5

addons:
  apt:
    packages:
    - python2.7

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 libsnappy-dev zlib1g-dev libbz2-dev -qq
  - export CXX="g++-4.8" CC="gcc-4.8"
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags2_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags2_2.0-1.1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags-dev_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_amd64.deb

install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - ./scripts/travis/get-rocksdb.sh
  - pip install ccm
  - pip install cqlsh=4.1.1
  - ccm create test -v 2.2.8 -n 1 -s
  - make bins

script:
 - make cover_ci
